const tasks = {
  1: {
    id: 1,
    category: "Personal Growth",
    text_en: "Write down 3 things you’re grateful.",
    text_es: "Escribe 3 cosas por las que estás agradecido.",
  },
  2: {
    id: 2,
    category: "Personal Growth",
    text_en: "Spend 5 minutes meditating in silence.",
    text_es: "Dedica 5 minutos a meditar en silencio.",
  },
  3: {
    id: 3,
    category: "Personal Growth",
    text_en: "List one habit you want to improve.",
    text_es: "Haz una lista de un hábito que quieras mejorar.",
  },
  4: {
    id: 4,
    category: "Personal Growth",
    text_en: "Read a random Wikipedia article.",
    text_es: "Lee un artículo aleatorio de Wikipedia.",
  },
  5: {
    id: 5,
    category: "Personal Growth",
    text_en: "Practice 5 minutes of mindful breathing.",
    text_es: "Practica 5 minutos de respiración consciente.",
  },
  6: {
    id: 6,
    category: "Personal Growth",
    text_en: "Write a letter to your future self.",
    text_es: "Escribe una carta a tu yo futuro.",
  },
  7: {
    id: 7,
    category: "Personal Growth",
    text_en: "Memorize one short inspirational quote.",
    text_es: "Memoriza una cita corta inspiradora.",
  },
  8: {
    id: 8,
    category: "Personal Growth",
    text_en: "Reflect on one thing you learned this week.",
    text_es: "Reflexiona sobre una cosa que aprendiste esta semana.",
  },
  9: {
    id: 9,
    category: "Personal Growth",
    text_en: "List 3 positive things that happened today.",
    text_es: "Haz una lista de 3 cosas positivas que ocurrieron hoy.",
  },
  10: {
    id: 10,
    category: "Personal Growth",
    text_en: "Turn off notifications for 1 hour.",
    text_es: "Apaga las notificaciones durante 1 hora.",
  },
  11: {
    id: 11,
    category: "Food & Cooking",
    text_en: "Try a fruit you’ve never eaten before.",
    text_es: "Prueba una fruta que nunca hayas comido.",
  },
  12: {
    id: 12,
    category: "Food & Cooking",
    text_en: "Cook a dish without looking at a recipe.",
    text_es: "Cocina un plato sin mirar una receta.",
  },
  13: {
    id: 13,
    category: "Food & Cooking",
    text_en: "Drink only water for the next 6 hours.",
    text_es: "Bebe solo agua durante las próximas 6 horas.",
  },
  14: {
    id: 14,
    category: "Food & Cooking",
    text_en: "Learn to cook a dish from another country.",
    text_es: "Aprende a cocinar un plato de otro país.",
  },
  15: {
    id: 15,
    category: "Food & Cooking",
    text_en: "Make a smoothie with 3 ingredients.",
    text_es: "Haz un licuado con 3 ingredientes.",
  },
  16: {
    id: 16,
    category: "Food & Cooking",
    text_en: "Bake something simple.",
    text_es: "Hornea algo sencillo.",
  },
  17: {
    id: 17,
    category: "Food & Cooking",
    text_en: "Replace sugar with honey or fruit.",
    text_es: "Reemplaza el azúcar por miel o fruta.",
  },
  18: {
    id: 18,
    category: "Food & Cooking",
    text_en: "Try eating a meal with chopsticks.",
    text_es: "Intenta comer una comida con palillos.",
  },
  19: {
    id: 19,
    category: "Food & Cooking",
    text_en: "Prepare breakfast for someone else.",
    text_es: "Prepara el desayuno para otra persona.",
  },
  20: {
    id: 20,
    category: "Food & Cooking",
    text_en: "Cook using only ingredients you already have at home.",
    text_es: "Cocina usando solo ingredientes que ya tienes en casa.",
  },
  21: {
    id: 21,
    category: "Creativity & Hobbies",
    text_en: "Draw something you see right now.",
    text_es: "Dibuja algo que veas en este momento.",
  },
  22: {
    id: 22,
    category: "Creativity & Hobbies",
    text_en: "Write a 4-line poem.",
    text_es: "Escribe un poema de 4 versos.",
  },
  23: {
    id: 23,
    category: "Creativity & Hobbies",
    text_en: "Take 3 photos of interesting textures.",
    text_es: "Toma 3 fotos de texturas interesantes.",
  },
  24: {
    id: 24,
    category: "Creativity & Hobbies",
    text_en: "Invent a short story about a random object.",
    text_es: "Inventa una historia corta sobre un objeto al azar.",
  },
  25: {
    id: 25,
    category: "Creativity & Hobbies",
    text_en: "Make a playlist with 5 songs you like.",
    text_es: "Haz una lista de reproducción con 5 canciones que te gusten.",
  },
  26: {
    id: 26,
    category: "Creativity & Hobbies",
    text_en: "Try sketching with your non-dominant hand.",
    text_es: "Intenta dibujar con tu mano no dominante.",
  },
  27: {
    id: 27,
    category: "Creativity & Hobbies",
    text_en: "Record yourself humming a melody.",
    text_es: "Grábate tarareando una melodía.",
  },
  28: {
    id: 28,
    category: "Creativity & Hobbies",
    text_en: "Fold a paper airplane and fly it.",
    text_es: "Haz un avión de papel y lánzalo.",
  },
  29: {
    id: 29,
    category: "Creativity & Hobbies",
    text_en: "Write down 5 ideas for a new project.",
    text_es: "Escribe 5 ideas para un nuevo proyecto.",
  },
  30: {
    id: 30,
    category: "Creativity & Hobbies",
    text_en: "Make a simple collage with paper scraps.",
    text_es: "Haz un collage sencillo con recortes de papel.",
  },
  31: {
    id: 31,
    category: "Movement & Health",
    text_en: "Do 10 pushups or as many as you can.",
    text_es: "Haz 10 flexiones o tantas como puedas.",
  },
  32: {
    id: 32,
    category: "Movement & Health",
    text_en: "Take the stairs instead of the elevator.",
    text_es: "Sube por las escaleras en lugar del ascensor.",
  },
  33: {
    id: 33,
    category: "Movement & Health",
    text_en: "Stretch for 5 minutes before bed.",
    text_es: "Haz estiramientos durante 5 minutos antes de dormir.",
  },
  34: {
    id: 34,
    category: "Movement & Health",
    text_en: "Go for a 15-minute walk.",
    text_es: "Da un paseo de 15 minutos.",
  },
  35: {
    id: 35,
    category: "Movement & Health",
    text_en: "Dance to your favorite song.",
    text_es: "Baila al ritmo de tu canción favorita.",
  },
  36: {
    id: 36,
    category: "Movement & Health",
    text_en: "Do 20 squats.",
    text_es: "Haz 20 sentadillas.",
  },
  37: {
    id: 37,
    category: "Movement & Health",
    text_en: "Try balancing on one leg for 1 minute.",
    text_es: "Intenta mantenerte en un pie durante 1 minuto.",
  },
  38: {
    id: 38,
    category: "Movement & Health",
    text_en: "Do 30 jumping jacks.",
    text_es: "Haz 30 saltos de tijera.",
  },
  39: {
    id: 39,
    category: "Movement & Health",
    text_en: "Try a basic yoga pose.",
    text_es: "Prueba una postura básica de yoga.",
  },
  40: {
    id: 40,
    category: "Movement & Health",
    text_en: "Walk outside without headphones.",
    text_es: "Camina afuera sin auriculares.",
  },
  41: {
    id: 41,
    category: "Social & Community",
    text_en: "Send a kind message to a friend.",
    text_es: "Envía un mensaje amable a un amigo.",
  },
  42: {
    id: 42,
    category: "Social & Community",
    text_en: "Give a genuine compliment to someone.",
    text_es: "Haz un cumplido sincero a alguien.",
  },
  43: {
    id: 43,
    category: "Social & Community",
    text_en: "Call a relative you haven’t spoken to in a while.",
    text_es: "Llama a un familiar con el que no hables hace tiempo.",
  },
  44: {
    id: 44,
    category: "Social & Community",
    text_en: "Leave a positive review for a local business.",
    text_es: "Deja una reseña positiva de un negocio local.",
  },
  45: {
    id: 45,
    category: "Social & Community",
    text_en: "Smile at a stranger.",
    text_es: "Sonríe a un desconocido.",
  },
  46: {
    id: 46,
    category: "Social & Community",
    text_en: "Hold the door open for someone.",
    text_es: "Sostén la puerta abierta para alguien.",
  },
  47: {
    id: 47,
    category: "Social & Community",
    text_en: "Ask someone about their favorite book.",
    text_es: "Pregunta a alguien por su libro favorito.",
  },
  48: {
    id: 48,
    category: "Social & Community",
    text_en: "Share an inspiring quote online.",
    text_es: "Comparte una cita inspiradora en línea.",
  },
  49: {
    id: 49,
    category: "Social & Community",
    text_en: "Say thank you to someone who helped you.",
    text_es: "Da las gracias a alguien que te haya ayudado.",
  },
  50: {
    id: 50,
    category: "Social & Community",
    text_en: "Donate one item you don’t need.",
    text_es: "Dona un objeto que no necesites.",
  },
  51: {
    id: 51,
    category: "Exploration",
    text_en: "Walk a different route than usual.",
    text_es: "Camina por una ruta diferente a la habitual.",
  },
  52: {
    id: 52,
    category: "Exploration",
    text_en: "Visit a new café or store.",
    text_es: "Visita un café o tienda nuevos.",
  },
  53: {
    id: 53,
    category: "Exploration",
    text_en: "Look at the stars for 5 minutes.",
    text_es: "Mira las estrellas durante 5 minutos.",
  },
  54: {
    id: 54,
    category: "Exploration",
    text_en: "Take 3 photos of your neighborhood.",
    text_es: "Toma 3 fotos de tu barrio.",
  },
  55: {
    id: 55,
    category: "Exploration",
    text_en: "Search for a local event happening today.",
    text_es: "Busca un evento local que ocurra hoy.",
  },
  56: {
    id: 56,
    category: "Exploration",
    text_en: "Read about a country you’ve never visited.",
    text_es: "Lee sobre un país que nunca hayas visitado.",
  },
  57: {
    id: 57,
    category: "Exploration",
    text_en: "Explore the oldest building nearby.",
    text_es: "Explora el edificio más antiguo cercano.",
  },
  58: {
    id: 58,
    category: "Exploration",
    text_en: "Take a bus or train to a random stop.",
    text_es: "Toma un colectivo o tren hasta una parada al azar.",
  },
  59: {
    id: 59,
    category: "Exploration",
    text_en: "Find out who your street was named after.",
    text_es: "Averigua en honor a quién fue nombrada tu calle.",
  },
  60: {
    id: 60,
    category: "Exploration",
    text_en: "Walk into a shop you’ve never entered.",
    text_es: "Entra en una tienda en la que nunca hayas entrado.",
  },
  61: {
    id: 61,
    category: "Small Skills",
    text_en: "Learn to tie a new knot.",
    text_es: "Aprende a hacer un nudo nuevo.",
  },
  62: {
    id: 62,
    category: "Small Skills",
    text_en: "Practice writing your name with your other hand.",
    text_es: "Practica escribir tu nombre con la otra mano.",
  },
  63: {
    id: 63,
    category: "Small Skills",
    text_en: "Learn one word in sign language.",
    text_es: "Aprende una palabra en lenguaje de señas.",
  },
  64: {
    id: 64,
    category: "Small Skills",
    text_en: "Try a new keyboard shortcut.",
    text_es: "Prueba un atajo nuevo del teclado.",
  },
  65: {
    id: 65,
    category: "Small Skills",
    text_en: "Memorize a phone number.",
    text_es: "Memoriza un número de teléfono.",
  },
  66: {
    id: 66,
    category: "Small Skills",
    text_en: "Balance a book on your head for 1 minute.",
    text_es: "Equilibra un libro en tu cabeza durante 1 minuto.",
  },
  67: {
    id: 67,
    category: "Small Skills",
    text_en: "Whistle a simple tune.",
    text_es: "Silba una melodía sencilla.",
  },
  68: {
    id: 68,
    category: "Small Skills",
    text_en: "Learn a basic magic trick.",
    text_es: "Aprende un truco de magia básico.",
  },
  69: {
    id: 69,
    category: "Small Skills",
    text_en: "Fold a fitted sheet properly.",
    text_es: "Dobla una sábana ajustable correctamente.",
  },
  70: {
    id: 70,
    category: "Small Skills",
    text_en: "Estimate the total of your grocery bill before paying.",
    text_es: "Estima el total de tu compra antes de pagar.",
  },
  80: {
    id: 80,
    category: "Small Skills",
    text_en: "Draw a self portrait.",
    text_es: "Dibuja un autoretrato.",
  },
  81: {
    id: 81,
    category: "",
    text_en: "Sing a song in another language.",
    text_es: "Canta una canción en otro idioma.",
  },
  82: {
    id: 82,
    category: "",
    text_en: "Take a silly picture of your pet.",
    text_es: "Toma una foto graciosa de tu mastoca.",
  },
  83: {
    id: 83,
    category: "",
    text_en: "Say the alphabet backwards.",
    text_es: "Dí el alfabeto al revés.",
  },
  84: {
    id: 84,
    category: "",
    text_en: "Try to make an animal with your hands' shadow.",
    text_es: "Intenta hacer un animal con la sombra de las manos.",
  },
  85: {
    id: 85,
    category: "",
    text_en: "Time how long you can hold your breath.",
    text_es: "Cuenta por cuánto tiempo puedes mantener la respiración.",
  },
  86: {
    id: 86,
    category: "",
    text_en: "Take a picture of a bird.",
    text_es: "Toma una foto de un pájaro.",
  },
  87: {
    id: 87,
    category: "",
    text_en:
      "Start a timer, try to stop it at 30 seconds without looking at it.",
    text_es:
      "Inicia un cronómetro, trata de pararlo en 30 segundos sin mirarlo.",
  },
};

const totalTasks = Object.keys(tasks).length;

/*
  80: {
    id: 80,
    category: "",
    text_en: "",
    text_es: "",
  },
*/
